name: Setup and install with pnpm

runs:
  using: composite
  steps:
    - name: Install pnpm 10
      uses: pnpm/action-setup@v4
      with:
        run_install: false
        version: 10.2.0

    - name: Install Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

