name: Pull Request Checks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited

jobs:
  conventional-commits:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
          wip: true

  lint-test-build:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    if: github.event.action != 'edited' && github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4

      - name: Setup and install
        uses: ./.github/actions/setup-and-install

      - name: Run linters
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Run builds
        run: pnpm build
