on:
  push:
    branches:
      - main

name: release-please

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT_RELEASE_PLEASE }}
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
