on:
  push:
    branches:
      - main

name: release-please

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PAT_RELEASE_PLEASE }}
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup and install
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/setup-and-install
  
      - name: Run tests
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm test
        
      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build
  
      - name: Publish package
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}