on:
  push:
    branches:
      - main

name: release-please


jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT_RELEASE_PLEASE }}
          target-branch: main
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish-package:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup and install
        uses: ./.github/actions/setup-and-install

      - name: Run tests
        run: pnpm test
        
      - name: Build package
        run: pnpm build

      - name: Publish package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
